import { motion, useReducedMotion, useScroll, useTransform } from 'motion/react';
import { useRef } from 'react';
import { profile } from '@/data/profile';

/**
 * The hero portrait.
 *
 * A real photograph of Sandeep, served as AVIF with WebP and JPEG fallbacks at
 * three widths (generated by scripts/optimize-images.mjs). The treatment around
 * it is deliberately quiet: one soft blue halo, a hairline ring, and a slow
 * parallax drift on scroll. No particle field, no sci-fi frame — the picture
 * should read as a photograph of a person, not a UI element.
 */
export function Portrait() {
  const containerRef = useRef<HTMLDivElement>(null);
  const prefersReduced = useReducedMotion();

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ['start end', 'end start'],
  });

  // A 28px drift across the full scroll range — perceptible as depth, not as
  // movement. Neutralised entirely when reduced motion is requested.
  const y = useTransform(scrollYProgress, [0, 1], prefersReduced ? [0, 0] : [18, -28]);

  return (
    <div ref={containerRef} className="relative mx-auto w-full max-w-[22rem] lg:max-w-[26rem]">
      {/* Ambient halo. Sits behind the photo and drifts on its own slow cycle. */}
      <div
        aria-hidden="true"
        data-decorative="motion"
        className="absolute -inset-10 -z-10 rounded-full bg-[radial-gradient(circle_at_50%_40%,rgb(0_191_255/0.18),transparent_68%)] blur-2xl [animation:halo-drift_14s_ease-in-out_infinite]"
      />

      {/* Static blue ground, kept separate so it survives reduced motion. */}
      <div
        aria-hidden="true"
        className="absolute -inset-6 -z-10 rounded-[2rem] bg-[radial-gradient(ellipse_at_50%_30%,rgb(0_191_255/0.09),transparent_70%)]"
      />

      <motion.div style={{ y }} className="relative">
        {/* Hairline ring, inset so it reads as a frame rather than a border. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 z-10 rounded-[1.5rem] ring-1 ring-inset ring-white/10"
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -inset-px z-10 rounded-[1.55rem] ring-1 ring-accent/20"
        />

        {/* Corner ticks — a small technical detail that frames the photo
            without enclosing it. */}
        {(
          [
            'left-3 top-3 border-l border-t',
            'right-3 top-3 border-r border-t',
            'left-3 bottom-3 border-b border-l',
            'right-3 bottom-3 border-b border-r',
          ] as const
        ).map((position) => (
          <span
            key={position}
            aria-hidden="true"
            className={`absolute z-20 size-4 border-accent/45 ${position}`}
          />
        ))}

        <picture>
          <source
            type="image/avif"
            srcSet="/media/portrait-400.avif 400w, /media/portrait-640.avif 640w, /media/portrait-900.avif 900w"
            sizes="(max-width: 1024px) min(80vw, 22rem), 26rem"
          />
          <source
            type="image/webp"
            srcSet="/media/portrait-400.webp 400w, /media/portrait-640.webp 640w, /media/portrait-900.webp 900w"
            sizes="(max-width: 1024px) min(80vw, 22rem), 26rem"
          />
          <img
            src="/media/portrait-640.jpg"
            srcSet="/media/portrait-400.jpg 400w, /media/portrait-640.jpg 640w, /media/portrait-900.jpg 900w"
            sizes="(max-width: 1024px) min(80vw, 22rem), 26rem"
            width={640}
            height={800}
            alt={`${profile.name}, wearing a dark blazer, standing with arms folded`}
            // Above the fold and preloaded in index.html: eager and high
            // priority, never lazy.
            loading="eager"
            fetchPriority="high"
            decoding="async"
            className="relative w-full rounded-[1.5rem] object-cover"
          />
        </picture>

        {/* Grounding gradient: fades the photo's base into the page so it does
            not sit on the background like a pasted rectangle. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-x-0 bottom-0 z-[5] h-28 rounded-b-[1.5rem] bg-gradient-to-t from-bg/85 via-bg/20 to-transparent"
        />
      </motion.div>

      {/* Status chip. Anchored to the frame, overlapping its lower edge. */}
      <div className="absolute -bottom-4 left-1/2 z-30 -translate-x-1/2">
        <div className="flex items-center gap-2.5 rounded-full border border-hairline-accent bg-bg/90 px-4 py-2 backdrop-blur-md">
          <span className="relative flex size-1.5">
            <span
              data-decorative="motion"
              className="absolute inline-flex size-full animate-ping rounded-full bg-accent opacity-70"
            />
            <span className="relative inline-flex size-1.5 rounded-full bg-accent" />
          </span>
          <span className="whitespace-nowrap text-[0.6875rem] font-medium tracking-wide text-fg-secondary">
            Open to internships &amp; freelance
          </span>
        </div>
      </div>
    </div>
  );
}
